### ISSUE TITLE
Package for CentOS 7

### ISSUE THREAD

**Issue by karthakon** [gozora/ebiso#11]
Is there any chance your could create a package for CentOS 7?

**Comment by gozora** [comment]
Should not be a problem, I'll take a look tomorrow.

V.

**Comment by gozora** [comment]
Hello @karthakon,

Centos 7 package build just finished. You can download it either from [OBS](https://download.opensuse.org/repositories/home:/gozora/CentOS_7/x86_64/) or from my [personal site](http://www.gozora.sk/c/ebiso/RPM/Centos/7/).

Hope it helps.

V.

**Comment by karthakon** [comment]
Thanks a lot!

**Comment by gozora** [comment]
No problem.
