### ISSUE TITLE
RPM is missing

### ISSUE THREAD

**Issue by gdha** [gozora/ebiso#2]
please try to create rpm builds (you can use OpenSuse Build Service for this). Would be easier to download binary rpms to use immediately on SLES architectures.
Thanks for EFI Boot ISO maker.... glad we have something working now on SLES/UEFI systems.

**Comment by gozora** [comment]
That is interesting idea, it can be definitely useful.
Currently I'm working on correct implementation of long file names (Rock Ridge standard), once it is released, I'll certainly take a look on RPM for SuSE distribution.

**Comment by gozora** [comment]
@gdha sorry that it took so long, but Rock Ridge is harder to implement than I initially thought...
RPM for SLES11 is now available in **packaging** directory of the project ([SLES11 RPM](https://github.com/gozora/ebiso/tree/master/packaging/SLES11)).

V.

**Comment by gdha** [comment]
@gozora where is the `ebiso.spec` file? Otherwise, I write some extra rules in the Makefile to build automatically and use OBS

**Comment by gozora** [comment]
@gdha https://github.com/gozora/ebiso/blob/master/packaging/SLES11/.spec/ebiso-0.1.1.x86_64.spec
